from jinja2 import Template
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
  body { font-family: 'Inter', Arial, sans-serif; margin: 0; padding: 0; color: #1a1a2e; }
  .cover { background: #0a0e14; color: white; padding: 60px 50px; min-height: 200px; }
  .cover h1 { font-size: 32px; color: #e8a020; margin: 0 0 8px; letter-spacing: 2px; }
  .cover h2 { font-size: 20px; font-weight: 300; color: #94a3b8; margin: 0 0 30px; }
  .cover .attendee-name { font-size: 28px; font-weight: 700; border-left: 4px solid #e8a020; padding-left: 16px; }
  .cover .meta { margin-top: 24px; font-size: 13px; color: #64748b; }
  .section { padding: 30px 50px; border-bottom: 1px solid #e2e8f0; }
  .section h3 { font-size: 16px; color: #0a0e14; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 16px; border-bottom: 2px solid #e8a020; padding-bottom: 8px; }
  .narrative { font-size: 14px; line-height: 1.7; color: #374151; background: #f8fafc; padding: 20px; border-radius: 6px; border-left: 4px solid #3b82f6; }
  .match-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 18px; margin-bottom: 14px; }
  .match-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px; }
  .match-name { font-size: 16px; font-weight: 700; color: #0a0e14; }
  .match-role { font-size: 12px; color: #64748b; margin-top: 2px; }
  .score-badge { background: #e8a020; color: #0a0e14; font-weight: 700; font-size: 14px; padding: 6px 12px; border-radius: 20px; }
  .score-high { background: #10b981; color: white; }
  .match-reason { font-size: 13px; color: #374151; line-height: 1.5; margin-top: 8px; background: #f0fdf4; padding: 10px 14px; border-radius: 4px; border-left: 3px solid #10b981; }
  .category-pill { display: inline-block; font-size: 11px; background: #eff6ff; color: #3b82f6; border: 1px solid #bfdbfe; padding: 3px 10px; border-radius: 12px; margin-top: 8px; }
  .rank { display: inline-block; background: #0a0e14; color: #e8a020; width: 24px; height: 24px; border-radius: 50%; text-align: center; line-height: 24px; font-size: 12px; font-weight: 700; margin-right: 8px; }
  .footer { background: #0a0e14; color: #64748b; padding: 20px 50px; font-size: 11px; text-align: center; }
</style>
</head>
<body>

<div class="cover">
  <h1>LIQUID GAS WEEK ISTANBUL 2026</h1>
  <h2>Your Personal Intelligence Pack</h2>
  <div class="attendee-name">{{ attendee.full_name }}</div>
  <div class="meta">{{ attendee.job_title }} · {{ attendee.company }} · {{ attendee.country }}</div>
  <div class="meta" style="margin-top:8px">Generated by WLGA AI Suite · {{ date }}</div>
</div>

<div class="section">
  <h3>Your Istanbul Briefing</h3>
  <div class="narrative">{{ narrative }}</div>
</div>

<div class="section">
  <h3>Your Top {{ matches|length }} Recommended Connections</h3>
  {% for match in matches %}
  <div class="match-card">
    <div class="match-header">
      <div>
        <span class="rank">{{ loop.index }}</span>
        <span class="match-name">{{ match.attendee_b.full_name }}</span>
        <div class="match-role" style="margin-left:32px">{{ match.attendee_b.job_title }} · {{ match.attendee_b.company }} · {{ match.attendee_b.country }}</div>
      </div>
      <span class="score-badge {% if match.score >= 85 %}score-high{% endif %}">{{ match.score }}%</span>
    </div>
    <span class="category-pill">{{ match.category }}</span>
    <div class="match-reason">{{ match.reason }}</div>
  </div>
  {% endfor %}
</div>

<div class="footer">
  WLGA Istanbul 2026 AI Suite · Confidential · Generated for {{ attendee.full_name }} only · worldliquidgas.org
</div>

</body>
</html>
"""

def generate_intelligence_pack_pdf(attendee: dict, matches: list, narrative: str) -> bytes:
    """Generate a branded PDF Intelligence Pack using WeasyPrint."""
    from weasyprint import HTML
    
    template = Template(HTML_TEMPLATE)
    html_content = template.render(
        attendee=attendee,
        matches=matches[:20],
        narrative=narrative,
        date=datetime.now().strftime("%B %d, %Y")
    )
    
    pdf = HTML(string=html_content).write_pdf()
    return pdf
