import { UN_DOCUMENTS, getUpcomingSessions } from "../../data/unAdvocacyData";

const criticalCount = UN_DOCUMENTS.filter((d) => d.flagPriority === "critical").length;
const readyPacks = getUpcomingSessions().filter((s) => s.briefingPackReady).length;

export default function AdvocacyStats() {
  const cards = [
    { value: "47", label: "WLGA cited in UN/multilateral documents (2020–2026)", trend: "+12 vs previous 6 years", color: "#4A90D9", icon: "📌" },
    { value: `${UN_DOCUMENTS.length}`, label: "UN documents flagged with LPG mentions — last 30 days", trend: null, color: "#4A90D9", icon: "📄" },
    { value: `${criticalCount}`, label: "Documents requiring urgent WLGA response", trend: "Critical", color: "#F85149", icon: "🚨" },
    { value: `${readyPacks}`, label: "Pre-session briefing packs generated by AI", trend: null, color: "#4A90D9", icon: "🎒" },
  ];

  return (
    <div className="px-8 py-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      {cards.map((c) => (
        <div key={c.label} className="advocacy-surface border advocacy-border rounded-lg p-5">
          <span className="text-2xl">{c.icon}</span>
          <p className="text-2xl font-bold mt-2" style={{ color: c.color }}>{c.value}</p>
          <p className="text-[#8B949E] text-sm">{c.label}</p>
          {c.trend && <p className="text-xs mt-1" style={{ color: c.color }}>{c.trend}</p>}
        </div>
      ))}
    </div>
  );
}
